---
- name: S'assurer que UFW est installé
  apt:
    name: ufw
    state: present

- name: "UFW | Autoriser SSH (Port 22)"
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp
    comment: "Accès SSH Admin"

- name: "UFW | Activer le pare-feu (Deny par défaut)"
  community.general.ufw:
    state: enabled
    policy: deny
    logging: on
