---
- name: DÃ©ploiement du Monitoring et Inventaire (Zabbix + GLPI)
  hosts: linux
  become: yes

  roles:
    - common         # Toujours le socle commun en premier
    - zabbix_agent   # Surveillance
    - glpi_agent     # Inventaire
